### ISSUE TITLE
 Is there a reason your team decided to only use ICD9 codes and not include ICD10 to identify suspicion of infection?

### ISSUE THREAD

**Issue by harshblue** [instigatorofawe/shockalert-documented#1]
@instigatorofawe, thank you for sharing your excellent research on Sepsis. In your analysis on eICU specifically "analyze_suspected_infection_icd9_eicu.R" your team seems to have only included ICD9 codes to identify patients with Suspected Infection. eICU includes both ICD9 and ICD10 in the diagnosis table, and as a result your cohort might have ended up smaller. 

Is there a reason your team decided to only use ICD9 codes and not include ICD10 to identify suspicion of infection?

Thanks for your time.

--Sree

**Comment by instigatorofawe** [comment]
@harshblue We use ICD-9 codes to determine suspected infection for continuity with other studies in the literature. [Angus et al. 2004 "Epidemiology of Severe Sepsis in the United States"](https://pubmed.ncbi.nlm.nih.gov/11445675/) lists ICD-9 codes corresponding to suspected infection which other studies have used in their evaluation of sepsis criteria.
