### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by carlofcti1983** [instigatorofawe/shockalert-documented#3]
Hi,

Thank you for your code. Please, can you verify what code should be ran before the 7. query_is_adult.R? This code needs the files clinical.data.mimic.rds and the processed/sofa_scores.rds, but they are not provided yet.

Regards

**Comment by instigatorofawe** [comment]
See https://github.com/instigatorofawe/shockalert-documented/issues/4#issue-631955139. You'll have to run eval_sepsis3_mimic_v3.R first in order to generate the SOFA scores.
