### ISSUE TITLE
Missing script that generates icd9.infection.icustays.rds and has.matched.rds

### ISSUE THREAD

**Issue by ftagnin** [instigatorofawe/shockalert-documented#4]
First of all, congratulations on your work! 

I am trying to go through it step-by-step, following your guidance, but found a few bumps on the way:
1. As was previously reported, the script query_is_adult.R has to be run after the scripts that create the sofa scores. i.e after eval_sepsis3_mimic_v3.R.
2. The script generate_reference_data_mimic_2.R reads a file called icd9.infection.icustays.rds that was not generated in the previous scripts. In fact, some scripts use this file, but no script creates it. 
3. Also as mentioned before here, other scripts use the file has.matched.rds that has not been generated by a previous script.

In order for me to proceed, is it possible to share the missing scripts?

Thank you!

**Comment by aram4934** [comment]
Hello! I am also trying to go through this script step-by-step and have run into these same problems. Would appreciate any guidance on how to solve this from either the creators or any fellow coders!
This is an amazing piece of work!

**Comment by instigatorofawe** [comment]
@ftagnin @aram4934 sorry for the delay; I've pushed the code that computes suspected infection from ICD-9 codes; the criteria therein are specified by [Angus et al. 2004](https://pubmed.ncbi.nlm.nih.gov/11445675/). has.matched.rds is a relic of when we were working with the waveform files in the MIMIC-3 database; it shouldn't actually be necessary for any of the scripts, even if some of them may still try to load that file.

**Comment by aram4934** [comment]
Thank you for your help. I have also found that in final_concomitant_gru_replicates.R and final_icd9_gru_eicu_2.R, there is a call for lstm.reference.dataset.rdata which I don't believe has been generated by the earlier scripts.
Hope the holiday season is going well for you!

**Comment by instigatorofawe** [comment]
See commit https://github.com/instigatorofawe/shockalert-documented/commit/2aa8c65732556b36aa24c82e0c6d478f54fdd72b

**Comment by aram4934** [comment]
Thank you! There are 3 more files in the eicu processing sequence that I'm not able to generate. These are eicu/patient_data.rds, eicu.reference.rdata and eicu.lstm.test.rdata. I don't believe the first two are used in the processing but wanted to confirm.

**Comment by ftagnin** [comment]
Thank you Ran for following up on this. I have actually created all the scripts from scratch in Python, and I'm now looking for a way to share them here in GitHub. I will try to do this in the next weeks. Your work has been instrumental in my research, although I am still way behind on the ML risk modeling you have done.

**Comment by aram4934** [comment]
The last one I've found to be missing is the script that creates icd9.lstm.reference.dataset.rdata (in addition to eicu.lstm.test.rdata mentioned earlier) as loaded in final_icd9_gru_eicu_2.R. The other two I mentioned before weren't used in the processing as far as I could tell.
I will update if I find any other omissions in generating the figures!
Thank you for your follow ups on this so far.

**Comment by instigatorofawe** [comment]
I'll take a look this weekend; those are for generating the timeseries data from eICU for external validation of the RNN method.
I honestly would not recommend using Keras in R, though. Actually, my current GPU doesn't even support versions of tensorflow older than the latest update of 2.4, so it might be somewhat difficult for me to provide support on that code, as it's dependent on older libraries.

Much better to use tensorflow in Python, and import your data from rds files via rpy2.

**Comment by aram4934** [comment]
Thank you for following up on this Ran. I have made my own edits to the scripts uploaded to generate the files I mentioned for my own learning.

I'm doing a research project as part of medical school on septic shock prediction using the eICU database and am hoping to use your code as a guide. Once I make progress, I will share this here on GitHub. Having not done machine learning since my undergrad, it looks like my knowledge is a bit outdated. As such, I will take your advice on Python in hand, thank you!

**Comment by instigatorofawe** [comment]
@aram4934 https://github.com/instigatorofawe/shockalert-documented/pull/5
This latest commit should resolve the missing files. I've also refactored the directory structure of this repository into something more usable.
